---
- name: Setup DNS
  hosts: centosdns
  become: true
  
  tasks:
#   VM Hostname
    - name: Set hostname to centosdns
      become: true
      ansible.builtin.hostname:
        name: centosdns.localdomain
        use: systemd

#   IP Configuration   
    - name: Add an Ethernet connection with static IP
      community.general.nmcli:
        conn_name: eth0
        ifname: eth0
        type: ethernet
        ip4: 192.168.98.12/24
        gw4: 192.168.98.10
        dns4: 192.168.98.12
        state: present       
    - name: Restart NetworkManager
      become: true
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

#   Install Packages      
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install nano
      ansible.builtin.dnf:
        name: nano
        state: latest
    - name: Install dnsmasq
      ansible.builtin.dnf:
        name: dnsmasq
        state: latest

#   DNS Server
    - name: Enable dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        enabled: true
        state: started
    - name: Set dnsmasq.conf
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/dnsmasq.conf"
        dest: /etc/dnsmasq.conf
        force: true
    - name: Set hosts
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/hosts"
        dest: /etc/hosts
        force: true
    - name: Restart dnsmasq
      become: true
      ansible.builtin.service:
        name: dnsmasq
        state: restarted