---
- name: Setup Database
  hosts: centosdb
  become: true
  
  tasks:
#   VM Hostname
    - name: Set hostname to centosdb
      become: true
      ansible.builtin.hostname:
        name: centosdb.localdomain
        use: systemd

#   IP Configuration 
    - name: Add an Ethernet connection with static IP
      community.general.nmcli:
        conn_name: eth0
        ifname: eth0
        type: ethernet
        ip4: 192.168.98.11/24
        gw4: 192.168.98.10
        dns4: 192.168.98.12
        state: present        
    - name: Restart NetworkManager
      become: true
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
               
#   Install Packages        
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install nano
      ansible.builtin.dnf:
        name: nano
        state: latest
    - name: Install DB
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Install python3-PyMySQL library
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present 
 
#   VM Configuration
    - name: Open firewall port 3306 TCP
      ansible.posix.firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
    - name: Reload Firewalld
      systemd:
        name: firewalld
        state: reloaded  
    - name: Start mysqld
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true         
    - name: Check & Enable mysqld
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: True

#   Database
    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: 'TNpasswd00.'
        state: present       
    - name: Create a new database with name 'nextjs_prisma'  
      community.mysql.mysql_db:
        name: nextjs_prisma
        state: present
        login_user: 'root'
        login_password: 'TNpasswd00.'              
    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: 'root'
        login_password: 'TNpasswd00.'   
    - name: Create database user with name 'nextjs' and password 'TNpasswd00' with all database privileges on nextjs_prisma
      community.mysql.mysql_user:
        name: nextjs
        password: TNpasswd00.
        host: '%'
        priv: 'nextjs_prisma.*:ALL,GRANT'
        state: present
        login_user: 'root'
        login_password: 'TNpasswd00.'

   