---
- name: Setup React App
  hosts: centos
  become: true
  
  tasks:
    - name: Install npm
      ansible.builtin.dnf:
        name: npm
        state: latest
    - name: Create Project Directory
      ansible.builtin.file:
        path: /home/vagrant/Test-App
        state: directory
        mode: '0755'
 