---
- name: Setup DB
  hosts: centosdb
  become: true
  
  tasks:
    - name: Set hostname to centosdb
      become: true
      ansible.builtin.hostname:
        name: centosdb.localdomain
        use: systemd
        
    - name: 'Set keyboard layout to: de-nodeadkeys'
      become: true 
      ansible.builtin.shell: 
        cmd: |
          if localectl status | grep -q 'VC Keymap: us'; then 
             sudo localectl set-keymap de-nodeadkeys ; fi
             
    - name: Change timezone to Europe/Berlin
      become: true 
      community.general.timezone:
        name: Europe/Berlin
      
                   
    - name: Check Proxy Settings
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^export no_proxy'
        state: absent
      check_mode: yes
      failed_when: false
      changed_when: false
      register: proxy_check  
      tags: proxy

    - name: Set Proxy Settings if not configured
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/environment"
        dest: /etc/environment
        force: true
      when: not proxy_check.found
      tags: proxy
      
    - name: Add an Ethernet connection with static IP
      community.general.nmcli:
        conn_name: eth0
        ifname: eth0
        type: ethernet
        ip4: 192.168.98.11/24
        gw4: 192.168.98.10
        dns4: 192.168.98.12
        state: present 
        
    - name: Restart NetworkManager
      become: true
      ansible.builtin.service:
        name: NetworkManager
        state: restarted        
        
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install nano
      ansible.builtin.dnf:
        name: nano
        state: latest

    - name: Install DB
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
        
    - name: Starten DB
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true    
        
    - name: Install MySQL client on CentOS 8
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Make sure mysqld service is running
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: True

    - name: Install python3-PyMySQL library
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present
         
    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: 'TNpasswd00.'
        state: present
        
    - name: Create a new database with name 'nextjs_prisma'  
      community.mysql.mysql_db:
        name: nextjs_prisma
        state: present
        login_user: 'root'
        login_password: 'TNpasswd00.'          
    
    
    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: 'root'
        login_password: 'TNpasswd00.'
    
    - name: Create database user with name 'nextjs' and password 'TNpasswd00' with all database privileges on nextjs_prisma
      community.mysql.mysql_user:
        name: nextjs
        password: TNpasswd00.
        priv: 'nextjs_prisma.*:ALL,GRANT'
        state: present
        login_user: 'root'
        login_password: 'TNpasswd00.'

   