---
- name: playbook for centOS hosts
  hosts: centOS
  
  tasks: 
  - name: ping test
    ansible.builtin.ping:
    tags: ping
    
  - name: check /etc/environment contains proxy settings
    ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^export no_proxy'
        state: absent
    check_mode: yes
    failed_when: false
    changed_when: false
    register: proxy_check  
    tags: proxy
    
  #- debug: var=proxy_check
   # tags: proxy
    
  - name: copy proxy settings if not configured
    become: true
    ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/environment"
        dest: /etc/environment
        force: true
    when: not proxy_check.found
    tags: proxy
  
  - name: Upgrade all packages
    become: true 
    dnf:  name="*" state=latest
    tags: pkgupgrade
  
  - name: set hostname to lnxhost
    become: true
    ansible.builtin.hostname:
       name: lnxhost.localdomain
       use: systemd

  - name: 'set keyboard layout to: de-nodeadkeys'
    become: true 
    ansible.builtin.shell: 
       cmd: |
          if localectl status | grep -q 'VC Keymap: us'; then 
             sudo localectl set-keymap de-nodeadkeys ; fi
             
  - name: change timezone to Europe/Berlin
    become: true 
    community.general.timezone:
        name: Europe/Berlin
